service: letsvalidate-api-aws-us-east-2
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: us-east-2

  # Not random, came up with based on good data based on timing API calls and seeing where more memory stopped making
  #     things faster
  #     https://docs.google.com/spreadsheets/d/1hOHOkk0FCqsmJAsbY-TeU08BNgfBc_G3dwv2Hl2Wzto/edit#gid=0
  memorySize: 768
  iam:
    role:
      statements:
        
        # Need to be able to read and write to Param Store -- store per-user Flickr OAuth token in Param Store
        - Effect: "Allow"
          Action:
            - "ssm:GetParameter"
            - "ssm:GetParameters"
            - "ssm:PutParameter"
          Resource: "arn:aws:ssm:us-east-2:959720795291:parameter/letsvalidate/*"


  httpApi:
    cors:
      allowedOrigins:
        - "https://letsvalidate.org"
        - "https://staging.letsvalidate-ui.pages.dev"
        - "https://dev-cody.letsvalidate-ui.pages.dev"
        - "https://dev-eric.letsvalidate-ui.pages.dev"
        - "https://dev-terry.letsvalidate-ui.pages.dev"
    authorizers:
      letsvJwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_YxLIxaw2F
        audience:
           - 1aq3d5q40ce3lhdijghi2pi1gn
           - 4qto2qut19rglo6h6aq7qi98ro
           - 78ich2vt28i9p89jf87mgg3qdq
           - hgd8grnghg8vtrmbj9u9gaf3l
           - sjra3i7iq5ptenkg379vsar2

constructs:
  worker-kv-updates:
    type: queue
    worker:
      handler: letsvalidate.util.aws_sqs.queue_worker

functions:

  oauth-callback:
    handler: cognito-oauth-callback.cognito_oauth_callback_webui_dev
    events:
      - httpApi:
          path: /oauth/callback/{environment}
          method: get

  api-add-url:
    handler: api-add-url.letsvalidate_api_add_url
    events:
      - httpApi:
          path: /api/v001/monitor
          method: post
          authorizer:
            name: letsvJwtAuthorizer
    environment:
      SQS_QUEUE_URL: ${construct:worker-kv-updates.queueUrl}

  api-remove-url:
    handler: api-remove-url.letsvalidate_api_remove_url
    events:
      - httpApi:
          path: /api/v001/monitor/{monitor_id}
          method: delete
          authorizer:
            name: letsvJwtAuthorizer
    environment:
      SQS_QUEUE_URL: ${construct:worker-kv-updates.queueUrl}


plugins:
  - serverless-lift
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

package:
  patterns:
    - "!node_modules/**"
